# reference: https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: py-lambda-circleci

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-1
  timeout: 45
  logRetentionInDays: 90
  deploymentBucket:
    name: ${self:service}-${self:provider.stage}-serverlessdeploymentbucket
  lambdaHashingVersion: 20201221


package:
  patterns:
  - '!.circleci/**'
  - '!requirements.txt'
  - '!README.md'
  - '!circleci-aws-iam.json'

functions:
  circle:
    handler: handler.lambda_handler
    description: AWS Lambda function to test CircleCI
    maximumRetryAttempts: 0
    events:
      - schedule:
          description: Calls CircleCI lambda function every hour
          rate: cron(0 */1 * * ? *)

plugins:
  - serverless-layers
  - serverless-deployment-bucket
custom:
  serverless-layers:
    dependenciesPath: ./requirements.txt
    compatibleRuntimes:
      - python3.8
  deploymentBucket:
    versioning: true
    accelerate: true
    blockPublicAccess: true
