# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
   aws-cli: circleci/aws-cli@2.0

jobs:
   deploy:
     docker:
       - image: cimg/python:3.8.10-node
     steps:
       - checkout
       - aws-cli/setup
       - run:
           name: Install Serverless CLI
           command: |
             # install
             curl -o- -L https://slss.io/install | bash
             echo 'export PATH=$HOME/.serverless/bin:$PATH' >> "$BASH_ENV"
             source "$BASH_ENV"
       - run:
           name: Install npm packages
           command: npm i
       - run:
           name: Deploy
           command: sls deploy -v

workflows:
  step-one:
    jobs:
      - deploy